### ISSUE TITLE
add some validation , privacy

### ISSUE THREAD

**Issue by abbasfisal** [stasyanko/laravel-large-project#7]
hi Thanks for sharing this prj

how we can add some validation or checking privacy or etc according to the design pattern and wich one of them is best for doing these ?

**Comment by stasyanko** [comment]
As far as I understand, you mean authentication by checking privacy? 

If so, Laravel implements it pretty well with [middlewares](https://laravel.com/docs/8.x/middleware).

Actually, middleware is very close to [Chain Of Responsibilities](https://designpatternsphp.readthedocs.io/en/latest/Behavioral/ChainOfResponsibilities/README.html) design pattern.

The only caveat about using middlewares - do not use things like `Auth::user()` in your middlewares to make them more testable.

Instead, inject a [subaction](https://github.com/stasyanko/laravel-large-project#subactions) with DI into a middleware.

If we talk about validation, I would implement it with a [decorator design pattern](https://designpatternsphp.readthedocs.io/en/latest/Structural/Decorator/README.html) by wrapping [actions](https://github.com/stasyanko/laravel-large-project#Actions) with a class which validates params passed to it.

But for simplicity I would use Laravel's built-in validation.
